# QUEST 9
__Plotly__

In [51]:
import pandas as pd
import sqlite3
import plotly.graph_objects as go
import numpy as np

In [52]:
database_path = "../data/checking-logs.sqlite"

In [53]:
try:
    connection = sqlite3.connect(database=database_path)
except Exception:
    print("The connection is failed :(")

## Создание таблицы

In [54]:
query = """
select timestamp, numTrials, uid from checker
where status = 'ready' and uid like 'user_%' and labname = 'project1'
"""
df = pd.io.sql.read_sql(query, connection, parse_dates="timestamp")
df["timestamp"] = df["timestamp"].dt.date

In [55]:
display(df)

      timestamp  numTrials      uid
0    2020-04-17          1   user_4
1    2020-04-17          2   user_4
2    2020-04-17          3   user_4
3    2020-04-17          4   user_4
4    2020-04-17          5   user_4
..          ...        ...      ...
946  2020-05-15         26  user_19
947  2020-05-15         27  user_19
948  2020-05-15         28  user_19
949  2020-05-15         27  user_28
950  2020-05-15         29  user_19

[951 rows x 3 columns]

In [56]:
display(df[df["uid"] == "user_18"])

      timestamp  numTrials      uid
296  2020-05-11          1  user_18
301  2020-05-11          2  user_18
302  2020-05-11          3  user_18
303  2020-05-11          4  user_18
304  2020-05-11          5  user_18
306  2020-05-11          6  user_18
307  2020-05-11          7  user_18
595  2020-05-13          8  user_18
771  2020-05-14          9  user_18
781  2020-05-14         10  user_18
792  2020-05-14         11  user_18
798  2020-05-14         12  user_18
876  2020-05-14         13  user_18
881  2020-05-14         14  user_18
914  2020-05-14         15  user_18
923  2020-05-14         16  user_18
924  2020-05-14         17  user_18
925  2020-05-14         18  user_18
927  2020-05-14         19  user_18
929  2020-05-14         20  user_18
930  2020-05-14         21  user_18
931  2020-05-14         22  user_18
933  2020-05-14         23  user_18
934  2020-05-14         24  user_18
935  2020-05-14         25  user_18
936  2020-05-14         26  user_18
938  2020-05-14         27  user_18
939  2020-05-14         28  user_18
940  2020-05-14         29  user_18
941  2020-05-14         30  user_18
942  2020-05-14         31  user_18

In [57]:
df = df.groupby(["timestamp", "uid"])["numTrials"].max().unstack()
df.index = np.arange(len(df.index))

In [58]:

df.iloc[0] = df.iloc[0].fillna(0, axis=0)
df.fillna(method="pad", axis=0, inplace=True)
#df = df.transpose()

In [59]:
display(df)

uid,user_1,user_10,user_11,user_12,user_13,user_14,user_15,user_16,user_17,user_18,...,user_26,user_27,user_28,user_29,user_3,user_30,user_31,user_4,user_6,user_8
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,11.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,20.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,27.0,0.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,35.0,0.0,0.0
7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,48.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,53.0,0.0,0.0
9,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,53.0,0.0,0.0
10,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,12.0,1.0,71.0,0.0,0.0
11,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,28.0,12.0,1.0,83.0,0.0,0.0
12,0.0,0.0,1.0,0.0,0.0,18.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,29.0,12.0,4.0,83.0,0.0,0.0
13,0.0,0.0,1.0,0.0,0.0,25.0,0.0,0.0,1.0,0.0,...,35.0,0.0,0.0,0.0,31.0,17.0,4.0,83.0,0.0,0.0
14,0.0,0.0,1.0,0.0,2.0,49.0,0.0,0.0,1.0,7.0,...,35.0,0.0,0.0,5.0,54.0,17.0,6.0,87.0,0.0,0.0
15,0.0,7.0,1.0,0.0,30.0,92.0,0.0,3.0,3.0,7.0,...,35.0,0.0,2.0,18.0,56.0,17.0,6.0,125.0,0.0,0.0
16,0.0,21.0,1.0,0.0,30.0,92.0,0.0,3.0,3.0,8.0,...,52.0,0.0,20.0,34.0,56.0,17.0,6.0,137.0,1.0,0.0
17,11.0,59.0,1.0,4.0,32.0,99.0,3.0,10.0,6.0,31.0,...,67.0,8.0,26.0,35.0,58.0,19.0,8.0,164.0,2.0,8.0
18,11.0,59.0,1.0,4.0,32.0,99.0,3.0,10.0,6.0,31.0,...,67.0,8.0,27.0,35.0,58.0,19.0,8.0,164.0,2.0,8.0

## Создание графика

Создадим 27 линий графика для динамики каждого пользователя:

In [60]:
initial_data = [go.Scatter(x=np.array([]), y =np.array([1]), mode = "lines+markers", name = uid) for uid in df.columns]

Создадим кадры для анимации для каждого пользователя - матрицу из значений функций в каждом x:

In [61]:
framess = []
for x in range(len(df.index)):
    frame = []
    for y in range(len(df.columns)):
        frame.append(go.Scatter(x=np.arange(x+1),
                                # y=np.array(df.loc[df.index < x, df.columns[y]]), # вывести значения колонки с индексом y где индекс таблицы меньше x
                                y = np.array(df.iloc[:(x+1), y]),
                                mode="lines+markers",
                                name=df.columns[y]
                                ))
    framme = {"data": frame}
    framess.append(framme)

In [62]:
fig = go.Figure(
    data=initial_data,
    layout={
        'width': 1100,
        'height': 500,
        'xaxis': {'range': (0,21)},
        'yaxis': {'range': (0, 160)},
        'title': 'Dynamic of commits per user in project1',
        'updatemenus': [{
            'type': 'buttons',
            'buttons': [{'method': 'animate', 'label': 'play', 'args': [None]}]
            }]}, frames=[{"data": f["data"]} for f in framess])     # список словарей с key = "data"
fig.show()

In [63]:
connection.close()