## QUEST 1

In [13]:
import pandas as pd

src_file = "../../feed-views.log"

## 1) Create a dataframe views with two columns

In [14]:
df = pd.read_csv(src_file, sep='\t', header=None)
df.columns=["datetime", "user"]

In [15]:
df

                        datetime       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:27:30.646665      artem
3     2020-04-17 12:35:44.884757      artem
4     2020-04-17 12:35:52.735016      artem
...                          ...        ...
1071  2020-05-21 18:45:20.441142  valentina
1072  2020-05-21 23:03:06.457819      maxim
1073  2020-05-21 23:23:49.995349      pavel
1074  2020-05-21 23:49:22.386789      artem
1075  2020-05-22 10:36:14.662600      artem

[1076 rows x 2 columns]

Проверка типов:

In [16]:
df.dtypes

datetime    object
user        object
dtype: object

Изменение типа datetime на datetime64:

In [17]:
df["datetime"] = df["datetime"].astype("datetime64")

In [18]:
df.dtypes

datetime    datetime64[ns]
user                object
dtype: object

Разбиение колонки datetime на year, month, day, hour, minute, and second:

In [19]:
df["year"] = df["datetime"].dt.year
df["month"] = df["datetime"].dt.month
df["day"] = df["datetime"].dt.day
df["hour"] = df["datetime"].dt.hour
df["minute"] = df["datetime"].dt.minute
df["second"] = df["datetime"].dt.second

In [20]:
df

,datetime,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076 entries, 0 to 1075
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   user      1076 non-null   object
 2   year      1076 non-null   int64
 3   month     1076 non-null   int64
 4   day       1076 non-null   int64
 5   hour      1076 non-null   int64
 6   minute    1076 non-null   int64
 7   second    1076 non-null   int64
dtypes: datetime64[ns](1), int64(6), object(1)
memory usage: 67.4+ KB

## 2) Create the new column daytime

Зададим колонку user ввиде ключа. Разделим колонку hour на иданные интервалы:

0 – 3.59 night, 4 – 6.59 early morning, 7 – 10.59 morning, 11 – 16.59 afternoon, 17 – 19.59 early evening, 20 – 23.59 evening

In [22]:
df["daytime"] = pd.cut(df["hour"], bins=[0, 4, 7, 11, 17, 20, 24], right=False, labels=["night", "early morning", "morning", "afternoon", "early evening", "evening"])
df.set_index("user", inplace=True)

In [23]:
df.head(n=10)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08.463179,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:23.743946,2020,4,17,12,1,23,afternoon
artem,2020-04-17 12:27:30.646665,2020,4,17,12,27,30,afternoon
artem,2020-04-17 12:35:44.884757,2020,4,17,12,35,44,afternoon
artem,2020-04-17 12:35:52.735016,2020,4,17,12,35,52,afternoon
oksana,2020-04-17 12:36:21.401412,2020,4,17,12,36,21,afternoon
oksana,2020-04-17 12:36:22.023355,2020,4,17,12,36,22,afternoon
artem,2020-04-17 13:55:19.129243,2020,4,17,13,55,19,afternoon
artem,2020-04-17 15:00:33.138530,2020,4,17,15,0,33,afternoon
artem,2020-04-17 15:14:09.581054,2020,4,17,15,14,9,afternoon

In [24]:
df.daytime.value_counts()

evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: daytime, dtype: int64

## 3) Сalculate the number of elements in your dataframe

calculate the number of elements in each time of day category using the method value_counts()

In [25]:
df["daytime"].value_counts()

evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: daytime, dtype: int64

## 4) Sort values in your dataframe by hour, minute, and second in ascending order (simultaneously and not one by one)

Отсортируем и заменим изначальный dataframe:

In [26]:
df.sort_values(by=["hour", "minute", "second"], inplace=True)

In [27]:
df

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

## 5) Calculate the minimum and maximum for the hours and the mode for the daytime categories

### 1. Calculate the maximum of hour for the rows where the time of day is night

In [28]:
night = df[df["daytime"] == "night"]  # строчки с night
hour_column = night["hour"] # выбираем из таблицы night только колонку hour
print(hour_column.max())

3

### 2. Calculate the minimum of hour for the rows where the time of day is morning

In [29]:
morning = df[df["daytime"] == "night"]
hour_column = morning["hour"]
min_morning = hour_column.max()
print(min_morning)
min_morning_table = df[df["hour"] == min_morning]
min_morning_table.index

3

Index(['konstantin', 'konstantin', 'konstantin'], dtype='object', name='user')

3. In addition to this, find out who visited the page at those hours (make one example from that)

In [30]:
min_morning_table = df[df["hour"] == min_morning]
min_morning_table.index

Index(['konstantin', 'konstantin', 'konstantin'], dtype='object', name='user')

4. Calculate the mode for the hour and daytime

In [31]:
df["hour"].mode()

0    22
dtype: int64

In [32]:
df["daytime"].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## 6) Show the 3 earliest hours in the morning and the corresponding usernames and the 3 latest hours and the usernames using nsmallest() and nlargest()

3 earlist hours:

In [33]:
morning_df = df[df["daytime"] == "morning"]
res = morning_df.nsmallest(n=3, columns="hour")
final = pd.DataFrame({"user":res.index, "hour":res["hour"]}) # без reset_index()
print(final.to_string(index=False))

     user  hour
alexander     8
alexander     8
alexander     9

3 latest ones:

In [34]:
morning_df = df[df["daytime"] == "morning"]
res = morning_df.nlargest(n=3, columns="hour")
final = pd.DataFrame({"user":res.index, "hour":res["hour"]}) # без reset_index()
print(final.to_string(index=False))

      user  hour
konstantin    10
     maxim    10
     maxim    10

## 7) Use the method describe() to get the basic statistics for the columns

In [35]:

df.describe()

         year        month          day         hour       minute       second
count  1076.0  1076.000000  1076.000000  1076.000000  1076.000000  1076.000000
mean   2020.0     4.870818    13.552974    16.249071    29.629182    29.500929
std       0.0     0.335557     4.906567     6.955490    17.689388    17.405506
min    2020.0     4.000000     1.000000     0.000000     0.000000     0.000000
25%    2020.0     5.000000    11.000000    13.000000    14.000000    14.000000
50%    2020.0     5.000000    13.000000    19.000000    29.000000    30.000000
75%    2020.0     5.000000    15.000000    22.000000    46.000000    45.000000
max    2020.0     5.000000    30.000000    23.000000    59.000000    59.000000

### Find out what the most popular interval for visiting the page is (interquartile range)

In [36]:
Q1 = df.describe()["hour"]["25%"]  # 25% часов находятся ниже этого часа Q1
Q3 = df.describe()["hour"]["75%"]  
iqr = Q3 - Q1
print(f"Q1 = {Q1}   Q3 = {Q3}")
print(f"iqr = {iqr}")

Q1 = 13.0   Q3 = 22.0
iqr = 9.0